[model]
img_size = [28, 28]
patch_size = [7,7]
in_channels = 1
num_classes = 9
embd_dim = 128
num_heads = 4
num_layers = 6
mlp_ratio = 4
dropout = 0.1

[training]
max_steps = 10000
warmup_steps = 1000
weight_decay = 0.1
betas = [0.9, 0.95]
lr = 3e-4
batch_size = 64

[data]
dataset = 'pathmnist'
data_dir = "./data"
num_workers = 4

[logging]
log_interval = 100
save_dir = "./outputs/"


